# General
--cookies-from-browser firefox
--js-runtimes bun
# Filesystem
--write-info-json
-o "E:/Videos/%(webpage_url_domain)s/%(uploader_id)s/%(upload_date>%Y-%m-%d)s_%(id)s.%(ext)s"
# Filter Format
-f "bestvideo[height<=720][vcodec^=av01]+bestaudio[acodec=opus]/bestvideo[height<=720][vcodec=vp9]+bestaudio/best"
# Thumbnail
#--write-thumbnail
# Post-Processing
--embed-thumbnail
--embed-metadata
--embed-chapters
--embed-info-json
--print-to-file "%(id)s,%(upload_date)s,%(webpage_url_domain)s,%(uploader_id)s,%(availability)s,%(title)s" "E:/Videos/videos.csv"
